### ISSUE TITLE
[ISSUE] Issue with `databricks_group` resource when using identity federation from account level

### ISSUE THREAD

**Issue by troyel** [databricks/terraform-provider-databricks#1709] opened 2022-10-31 15:43 UTC
The 'databricks_group' resources does not act as the workspace GUI when adding account groups to a workspace activated on Unity Catalog. Instead of assigning account level groups the terraform resource creates parallel workspace local groups.

![image](https://user-images.githubusercontent.com/22769102/199049106-74608751-6523-4509-9db8-db9e26366166.png)

### Configuration
```hcl
// first
// add databricks group at account level - to be later added at workspace level
resource "databricks_group" "account_level_group" {
  display_name = "group_abc"
}

// after
// add databricks group at workspace level
resource "databricks_group" "same_group_at_workspace" {
  display_name = "group_abc"
}

```

### Expected Behavior
1. The group "group_abc" is added to account level.
2. The same group "group_abc" is then assigned to the workspace referencing account level group

### Actual Behavior
1. The group "group_abc" is added to account level.
2. Anew "group_abc" is created on the workspace level as "Workspace local" group, not connected to the account level group.

### Terraform and provider versions
Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.0.0
+ provider registry.terraform.io/databricks/databricks v1.5.0
+ provider registry.terraform.io/hashicorp/azuread v2.29.0
+ provider registry.terraform.io/hashicorp/azurerm v3.1.0
+ provider registry.terraform.io/hashicorp/external v2.2.2

**Comment by alexott** [comment] 2022-10-31 15:44
Duplicate of #1703

**Closed by alexott** 2022-10-31 15:44 UTC
