### ISSUE TITLE
[Issue] 'Provider produced inconsistent result after apply' Error for SP associated job permission policies

### ISSUE THREAD

**Issue by vadivelselvaraj** [databricks/terraform-provider-databricks#1681] opened 2022-10-20 15:35 UTC
When trying to associate ownership for resources with a service principal using its `application_id`, I encounter the below TF error.
```
Error: Provider produced inconsistent result after apply
When applying changes to databricks_permissions.legacy_ownership_permissions[114], provider "provider[\"registry.terraform.io/databricks/databricks\"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Terrform code:**
```hcl
locals {
  all_job_ids = [
    databricks_job.a.id,
    databricks_job.b.id,
    databricks_job.c.id,
    databricks_job.d.id,
    databricks_job.e.id,
  ]
}

resource "databricks_permissions" "ownership_permissions" {
  count  = length(local.all_job_ids)
  job_id = local.all_job_ids[count.index]

  access_control {
    service_principal_name = local.deployment_user_service_principal_application_id
    permission_level       = "IS_OWNER"
  }
}
```

Notes:
- Databricks TF provider version: 1.5.0
- The Databricks workspace is Unity Catalog with Identity Federation enabled. The Service principal was created at the account level and assigned to the workspace using `databricks_mws_permission_assignment` TF resource.

**Comment by vadivelselvaraj** [comment] 2022-10-20 15:35
Tried this with the `1.6.0` TF provider version and it fails when trying to grant a Service Principal(using its `application_id`) owner permissions to a single job as below.

```hcl
resource "databricks_permissions" "legacy_ownership_permissions" {
  job_id = local.all_job_ids[0]

  access_control {
    service_principal_name = local.rivian_atlas_prod_deployment_user_sp_application_id
    permission_level       = "IS_OWNER"
  }
}
```

**Comment by nfx** [comment] 2022-10-20 16:12
@vadivelselvaraj is this something that was working before and doesn't work now?

**Comment by dcloud9** [comment] 2022-10-21 12:58
> @dcloud9 that's a separate bug, because it's a different resource. please file one with steps to reproduce.

I got one more bug in `databricks_dbfs_file` resource, but exactly same behaviour and workaround I put in.
```
  lifecycle {
    ignore_changes = [dbfs_path, file_size, id]
  }
```

**Comment by nfx** [comment] 2022-10-21 12:59
@dcloud9 a bug per resource+behavior, please ;) otherwise it will be forgotten about.

**Comment by nfx** [comment] 2022-10-21 13:00
@dcloud9 it's very important to know the versions of TF and debug logs.

**Comment by nfx** [comment] 2022-10-21 13:01
@vadivelselvaraj what is the terraform version, btw? did this behavior appear in the older terraform versions or the recent ones?

**Comment by vadivelselvaraj** [comment] 2022-10-21 13:13
> @vadivelselvaraj is this something that was working before and doesn't work now?

No. This is the first time I'm trying to grant job permissions to a Service Principal and it failed.

> @vadivelselvaraj what is the terraform version, btw? did this behavior appear in the older terraform versions or the recent ones?

I observed this for `1.5.0` and `1.6.0` versions.

**Comment by pietern** [comment] 2022-11-21 15:23
@vadivelselvaraj Can you confirm if this issue persists?

I tried to reproduce with the following steps:
1. Provision an SP at the account level
2. Use `databricks_mws_permission_assignment` to assign this SP to a workspace
3. Provision a test job in the same workspace
4. Use `databricks_permissions` to grant the SP `IS_OWNER` access to the job by its application ID (hard coded)

All steps succeeded with provider version 1.6.4 and Terraform version 1.2.9.

**Comment by vadivelselvaraj** [comment] 2022-11-29 17:46
@pietern The issue still persists.

**Notes:**
1. Databricks TF provider version: 1.6.5
2. Terraform core version: 1.0.0
3. Used the same TF code setup as outlined in the description.
4. I think you should be able to replicate the issue when you try to assign the ownership to a job that wasn't provisioned by the respective Service Principal.

**Comment by pietern** [comment] 2022-12-19 15:51
@vadivelselvaraj Thanks for the update. Could you clarify:
1) Which user provisioned the jobs and is their current owner?
2) Which user is running TF apply?

Regarding your point 4; I run as admin, provision an SP, provision a job (as admin), and assign ownership to the SP that was just provisioned, and this works. Are you by any chance running as the SP that you're trying to assign ownership to? If the current user doesn't have `CAN_MANAGE` on the job then it won't be able to assign ownership.

**Comment by pietern** [comment] 2023-01-06 11:12
I'm closing the issue due to inability to reproduce. Please feel free to reopen with more details if the issue persist.

**Closed as completed by pietern** 2023-01-06 11:12 UTC
Labels: Bug
