### ISSUE TITLE
[ISSUE] Issue with `databricks_model_serving` resource

### ISSUE THREAD

**Issue by renata-gotler** [databricks/terraform-provider-databricks#4064] opened 2024-10-01 17:37 UTC
### Configuration
I'm trying to update a model using databricks_model_serving. The first time it works, but when I try to deploy another version the error `Error: cannot update model serving: scaleToZeroEnabled is undefined. Please set it to either true or false.` doesn't let me. The plan is showing everything right, but it fails in the apply.

I tried setting scale_to_zero_enabled to false and to true, none worked.
```

### Expected Behavior
Update the model as the plan.

### Actual Behavior
Error.

### Steps to Reproduce
Deploy a model and then try to update its version to another using terraform.

### Terraform and provider versions
I'm using the latest version so far.
terraform {
  required_version = "~>1.8"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.101.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "1.52.0"
    }
  }
}


### Is it a regression?
<!-- Did this work in a previous version of the provider? If so, which versions did you try? -->

### Debug Output
<!-- Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply -no-color` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests. It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.: `TF_LOG=DEBUG terraform apply -no-color 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/' 2>&1 |tee tf-debug.log`. If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. -->

### Important Factoids
<!-- Are there anything atypical about your accounts that we should know? -->

### Would you like to implement a fix?
<!-- If you plan to implement a fix for this, let the maintainers and community know -->

**Comment by alexott** [comment] 2024-10-01 19:05
duplicate of #3946

**Comment by alexott** [comment] 2024-11-13 09:49
Closing as it's fixed on backend

**Closed by alexott** 2024-11-13 09:49 UTC
