### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource

### ISSUE THREAD

**Issue by ian-norris** [databricks/terraform-provider-databricks#2726] opened 2023-09-26 15:14 UTC
### Configuration
```hcl
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
    }
  }
}
```

### Expected Behavior

The `databricks_catalog` resource is created successfully.

### Actual Behavior

While using the Databricks providers in Terraform - There is some volatility with using the resource `databricks_catalog`. I’m going to provide the errors I see, however, sometimes this process works and there isn’t errors.

The `databricks_catalog` attempts creation, terraform responds with a failure message:

cannot read catalog: User does not have USE CATALOG on Catalog.

If I go into the workspace console the catalogs do exists. The owner of the catalogs is the specified group from the configuration. The `User` of the terraform providers is a member of this group. I’m not sure why I’m getting this error since the `User` is an owner of the catalog.

### Steps to Reproduce

`terraform apply`

### Terraform and provider versions

Using latest as of now (1.26.0)

**Comment by alexott** [comment] 2023-09-27 10:41
Could be a duplicate of #2421

**Comment by ian-norris-ncino** [comment] 2023-10-03 12:32
> Could be a duplicate of #2421

This issue looks a little different. This user is having issues with the CREATE_CATALOG on a metastore. We don't have that problem with ours after we granted our SP CREATE_CATALOG access on the metastore.

**Comment by nkvuong** [comment] 2023-10-09 08:12
@ian-norris-ncino if this was a foreign catalog then there was a bug in the backend which should be fixed by now

**Comment by ian-norris-ncino** [comment] 2023-10-09 13:23
@nkvuong Ah, well that is great to hear. It seems like we haven't experienced the error in a while. Do you know the version the fix was implemented?

**Comment by nkvuong** [comment] 2023-10-09 13:30
@ian-norris-ncino the fix is in our backend service, so does not require upgrading tf provider version. Do you mind closing this issue if the error has not come back in the next few days?

**Closed as completed** 2023-10-09 15:23 UTC
