### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_endpoint` resource

### ISSUE THREAD

**Issue by aru-trackunit** [databricks/terraform-provider-databricks#2011] opened 2023-02-16 10:21 UTC
Provider doesn't respect `enable_serverless_compute` property

### Configuration
```hcl
resource "databricks_sql_endpoint" "classic_warehouse" {
  name                      = "classic warehouse"
  cluster_size              = "X-Small"
  auto_stop_mins            = 15
  max_num_clusters          = 2
  enable_serverless_compute = false
  warehouse_type = "Classic"

  tags {
    custom_tags {
      key   = "env"
      value = "dev"
    }
  }
}
```

### Expected Behavior
After applying `enable_serverless_compute` flag is set to false

### Actual Behavior
```
Error: cannot update sql endpoint: Invalid warehouseType: Serverless is only available for PRO warehouses.
│ 
│   with databricks_sql_endpoint.airflow_classic_endpoint,
│   on databricks_sql_endpoint.tf line 47, in resource "databricks_sql_endpoint" "airflow_classic_endpoint":
│   47: resource "databricks_sql_endpoint" "airflow_classic_endpoint" {
```

### Steps to Reproduce
`terraform apply`

### Terraform and provider versions
```
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.9.2
+ provider registry.terraform.io/hashicorp/aws v4.54.0
+ provider registry.terraform.io/hashicorp/vault v3.12.0
```

### Debug Output

```
Terraform will perform the following actions:

# databricks_sql_endpoint.airflow_classic_endpoint will be updated in-place
  ~ resource "databricks_sql_endpoint" "airflow_classic_endpoint" {
      ~ enable_serverless_compute = false -> true
        id                        = "e2a685fb3bf0ebd3"
        name                      = "Airflow classic warehouse"
      ~ warehouse_type            = "PRO" -> "CLASSIC"
        # (10 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }


Plan: 0 to add, 1 to change, 0 to destroy.
```
then `terraform apply`
and then the error:
```
Error: cannot update sql endpoint: Invalid warehouseType: Serverless is only available for PRO warehouses.
│ 
│   with databricks_sql_endpoint.airflow_classic_endpoint,
│   on databricks_sql_endpoint.tf line 47, in resource "databricks_sql_endpoint" "airflow_classic_endpoint":
│   47: resource "databricks_sql_endpoint" "airflow_classic_endpoint" {
```

**Comment by alexott** [comment] 2023-02-16 10:34
Duplicate of #1436

**Closed by alexott** 2023-02-16 10:34 UTC
