### ISSUE TITLE
databricks_pipeline: terraform apply fails after modifying cluster configuration

### ISSUE THREAD

**Issue by ajarvelin** [databricks/terraform-provider-databricks#1409] opened 2022-06-28 08:41 UTC
### Affected Resource(s)
* https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline

### Example configuration
```
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.0.0"
    }
  }
}

data "databricks_current_user" "me" {
}

locals {
  pipeline_name   = "dlt_test_${data.databricks_current_user.me.alphanumeric}"
  notebook_target = "${data.databricks_current_user.me.home}/Terraform/${local.pipeline_name}/${local.pipeline_name}"
  storage_path    = "${data.databricks_current_user.me.home}/Terraform/${local.pipeline_name}"
}

resource "databricks_notebook" "notebook" {
  content_base64 = base64encode(<<-EOT
    # created from ${abspath(path.module)}
    import dlt

    json_path = "/databricks-datasets/wikipedia-datasets/data-001/clickstream/raw-uncompressed-json/2015_2_clickstream.json"
    @dlt.table(
        comment="The raw wikipedia clickstream dataset, ingested from /databricks-datasets."
    )
    def clickstream_raw():
        return (spark.read.format("json").load(json_path))
    EOT
  )
  path     = local.notebook_target
  language = "PYTHON"
}

resource "databricks_pipeline" "dlt_pipeline" {
  name    = local.pipeline_name
  channel = "CURRENT"
  storage = local.storage_path

  cluster {
    label       = "default"
    num_workers = 2
    custom_tags = {
      cluster_type = "default"
    }
  }

  library {
    notebook {
      path = databricks_notebook.notebook.id
    }
  }

  continuous = false
}
```

### Expected Behavior
After modifying the cluster configuration (e.g. setting `num_workers = 3`), `terraform apply` should run successfully. 

### Actual Behavior
`terraform apply` fails with message `Error: cannot update pipeline: clusters must have exactly 1 default cluster`.

### Steps to reproduce
1. Run `terraform init`
2. Run `terraform apply`, and confirm the deployment
3. Edit the cluster configuration, change e.g. `num_workers = 3`
4. Run `terraform apply`, and confirm the deployment. The deployment should now fail with the following error message:
   `Error: cannot update pipeline: clusters must have exactly 1 default cluster`

### Workaround
1. Remove the cluster configuration block
2. Run `terraform apply`
3. Add back the cluster configuration block with desired configuration change (e.g. `num_workers = 3`)
4. Run `terraform apply`, the deployment should be successful

### Terraform and provider versions
```
Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.0.0
```

### Debug output
```
2022-06-28T10:35:04.997+0200 [DEBUG] provider.terraform-provider-databricks_v1.0.0: PUT /api/2.0/pipelines/9d47410c-d8be-4c0b-8647-33531fc29101 {
  "channel": "CURRENT",
  "clusters": [
    {
      "custom_tags": {
        "cluster_type": "default"
      },
      "label": "default",
      "num_workers": 3
    },
    {}
  ],
  "edition": "advanced",
  "id": "9d47410c-d8be-4c0b-8647-33531fc29101",
  "libraries": [
    {
      "notebook": {
        "path": "--------------"
      }
    }
  ],
  "name": "dlt_test_antti_jarvelin",
  "storage": "---------------"
}: timestamp=2022-06-28T10:35:04.997+0200
2022-06-28T10:35:05.223+0200 [DEBUG] provider.terraform-provider-databricks_v1.0.0: 400 Bad Request {
  "error_code": "INVALID_PARAMETER_VALUE",
  "message": "clusters must have exactly 1 default cluster"
}: timestamp=2022-06-28T10:35:05.223+0200
2022-06-28T10:35:05.223+0200 [WARN]  provider.terraform-provider-databricks_v1.0.0: /api/2.0/pipelines/9d47410c-d8be-4c0b-8647-33531fc29101:400 - clusters must have exactly 1 default cluster https://docs.databricks.com/dev-tools/api/latest/pipelines.html#9d47410c-d8be-4c0b-8647-33531fc29101: timestamp=2022-06-28T10:35:05.223+0200
2022-06-28T10:35:05.223+0200 [WARN]  provider.terraform-provider-databricks_v1.0.0: /api/2.0/pipelines/9d47410c-d8be-4c0b-8647-33531fc29101:400 - clusters must have exactly 1 default cluster https://docs.databricks.com/dev-tools/api/latest/pipelines.html#9d47410c-d8be-4c0b-8647-33531fc29101: timestamp=2022-06-28T10:35:05.223+0200
2022-06-28T10:35:05.231+0200 [ERROR] vertex "databricks_pipeline.dlt_pipeline" error: cannot update pipeline: clusters must have exactly 1 default cluster
╷
│ Error: cannot update pipeline: clusters must have exactly 1 default cluster
│ 
│   with databricks_pipeline.dlt_pipeline,
│   on main.tf line 36, in resource "databricks_pipeline" "dlt_pipeline":
│   36: resource "databricks_pipeline" "dlt_pipeline" {

```

**Comment by nfx** [comment] 2022-06-28 13:38
Duplicate of #1401

**Closed by nfx** 2022-06-28 13:38 UTC
Labels: need explicit docs
