### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource and isolation_mode='ISOLATED'

### ISSUE THREAD

**Issue by marin6six** [databricks/terraform-provider-databricks#2446] opened 2023-06-29 14:33 UTC
### Configuration
```hcl
terraform {
  required_version = ">= 1.1.7"
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~>1.14"
    }
    aws = ">= 4.10"
  }
  backend "s3" {
    # Should be fed by the content of the config\$ENV.tfbackend file at run 
    # Example : terraform init -backend-config=config/sandbox.tfbackend
    # cf. https://www.terraform.io/language/settings/backends/configuration#partial-configuration
  }
}
```

### Expected Behavior
I added the new argument isolation_mode = 'ISOLATED' to make sure that my catalog is only visible from the workspace it is associated to. I would like to have a resource such like "databricks_workspace_assignment" where I can allow my catalog to be used only by a dedicated workspace. I did not find any resource like that.

### Actual Behavior
The catalog is created but no workspace has access to it. I also get this error when doing "apply" :
```
│ Error: cannot read catalog: Catalog 'sbx-datamanagement' is not accessible in current workspace
│ 
│   with module.datamanagement.module.unity_catalog.databricks_catalog.this["datamanagement"],
│   on modules/databricks_workspace/modules/unity_catalog/catalogs.tf line 38, in resource "databricks_catalog" "this":
│   38: resource "databricks_catalog" "this" {
```

### Steps to Reproduce
1. Create a databricks_catalog resource with argument `isolation_mode = 'ISOLATED'`
2. `terraform apply`

### Terraform and provider versions
Version 1.19 is used

**Comment by thaiphv** [comment] 2023-06-30 02:54
My understanding is that the Unity Catalog API is hosted on the workspace instead of the account level. When we want to deploy any UC resources on a workspace, for example a catalog or a metastore, they have to be assigned to the workspace first.
For this particular catalog resource, as it's in ISOLATED mode, before it can be refreshed from the workspace API, it has to be associated with the workspace. This becomes a chicken and egg problem. Even with the release of the `databricks_catalog_workspace_binding` resource, it still doesn't solve the problem.
This can only be solved when they move all the UC API to the account level.

**Comment by kunaljadhav-db** [comment] 2023-07-03 09:29
Hello @marin6six @thaiphv, I have tested this databricks_catalog, and the error "cannot read catalog: Catalog 'sandboxisolated3' is not accessible in current workspace" is reproducible with provider version 1.19.0. 
But with 1.20.0 you can create the catalog with isolated mode and it will be assigned to the current workspace as expected.

**Comment by awshumway** [comment] 2023-09-15 19:12
I'm experiencing this issue - I cannot modify an existing catalog to `isolation_mode` of `ISOLATED`, the catalog becomes "not accessible in the current workspace" and I have to recover it using an API command to revert it to `OPEN`. I also cannot create a new catalog with `isolation_mode` set to `ISOLATED`. 

I'm using Databricks provider versions 1.24.1 and 1.25.0

**Comment by tanmay-db** [comment] 2023-09-20 11:12
Hi @awshumway, can you please confirm if it's working for 1.20.0 for you?

**Comment by awshumway** [comment] 2023-09-21 18:13
Hi @tanmay-db, I have done some additional testing and found that with both versions 1.20.0 and 1.25.0 I experience the same behavior: 
- I can create catalogs with `isolation_mode` set to `ISOLATED` 
- I can create catalogs with `isolation_mode` set to `OPEN` 
- I can modify a catalog that was originally `ISOLATED` to `OPEN` 
- I CANNOT modify a catalog that was originally `OPEN` to `ISOLATED`

When I attempt this last action, I get an error of: `Error: cannot read catalog: Catalog 'testing_catalog' is not accessible in current workspace`.

In the UI I then observe the catalog symbol has a slash through it, it cannot be accessed, and it is not bound to any workspace. The checkbox "All workspaces have access" is unchecked. Here are some screenshots for clarification: 
![Catalog With No Access](https://github.com/databricks/terraform-provider-databricks/assets/46980348/f614ecdc-4df4-4cd0-b871-c67f14b9c8ce)
![Inaccessible Catalog Details](https://github.com/databricks/terraform-provider-databricks/assets/46980348/64e1ccf7-4b14-4b78-bb6c-fb61bcb9b378)

The [Databricks Terraform Provider documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/catalog#isolation_mode) describes that the `isolation_mode` attribute being set to `ISOLATED` will "automatically allow access from the current workspace". This seems to work for creating new catalogs, but not for modifying catalogs which were originally provisioned as available in all workspaces (open). 

In the [Databricks Documentation](https://docs.databricks.com/en/data-governance/unity-catalog/create-catalogs.html#optional-assign-a-catalog-to-specific-workspaces), the steps to isolate a catalog to a specific workspace in the UI include clearing the "All workspaces have access" checkbox (step 4) and assigning the catalog to a workspace (step 5).  In the case of converting an originally "open" catalog to "isolated" via Terraform, however, it appears that only step 4 from [the UI instructions](https://docs.databricks.com/en/data-governance/unity-catalog/create-catalogs.html#optional-assign-a-catalog-to-specific-workspaces) occurs, and the catalog becomes inaccessible because step 5 to associate the catalog with the current workspace doesn't occur.

**Comment by tanmay-db** [comment] 2023-09-22 15:08
Hi @awshumway, thanks for the detailed response. We are investigating the issue and will reach back with update.

**Comment by shreyas-goenka** [comment] 2023-09-28 23:28
@awshumway as stated earlier the issue is that the catalog API endpoint is tied to the workspace. We can work around this issue by using the `databricks_catalog_workspace_binding` resource (docs: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/catalog_workspace_binding)

Consider the catalog:
```
resource "databricks_catalog" "this" {
  name = "owner-test"
  isolation_mode = "OPEN"
}
```

You change change it to isolated by:
```
resource "databricks_catalog" "this" {
  depends_on = [ databricks_catalog_workspace_binding.name ]
  name = "owner-test"
  isolation_mode = "ISOLATED"
}

resource "databricks_catalog_workspace_binding" "this" {
  catalog_name = "owner-test"
  workspace_id = "WORKPSACE_ID"
}
```

If you wish to avoid the `depends_on` clause, you can also instead run terraform apply twice, with the first time introducing the `databricks_catalog_workspace_binding` resource and then changing "OPEN" -> "ISOLATED"

I believe this solves the problem. A proper fix would be do this automatically. I have filed a ticket in our internal backlog to do this when we get the chance.

Please feel free to reopen the issue if this workaround does not work for you.

**Closed by shreyas-goenka** 2023-09-28 23:28 UTC
