### ISSUE TITLE
[ISSUE] databricks_sql_permissions: permission on any_file always is not persisted in state

### ISSUE THREAD

**Issue by ebarault** [databricks/terraform-provider-databricks#1472] opened 2022-07-18 16:47 UTC
### Configuration
```hcl
resource "databricks_sql_permissions" "permissions" {

  any_file = true

  privilege_assignments {
      principal = "hive_metastore_users"
      privileges = ["SELECT"]
  }
}

```

### Expected Behavior
What should have happened?

Permissions are correctly configured during the first apply.
Next apply does not trigger the same changes.

### Actual Behavior
Permissions are correctly configured during the first apply.
Next apply endlessly trigger the same changes.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply` (second time)

### Terraform and provider versions
terraform version: 1.1.9
provider version: 1.0.2

**Comment by nkvuong** [comment] 2022-07-18 17:33
this is the same as #1245

**Comment by nfx** [comment] 2022-07-18 20:16
Duplicate of #1245

**Closed by nfx** 2022-07-18 20:16 UTC
Labels: bug
