### ISSUE TITLE
[FEATURE] Add Ability to Import `*mws*` Resources

### ISSUE THREAD

**Issue by nate-froiland** [databricks/terraform-provider-databricks#2194] opened 2023-04-05 21:10 UTC
### Use-cases
For resources not originally created via terraform, add the ability to import them into the terraform configuration and state.

For example, importing resources like `databricks_mws_workspaces`, `databricks_mws_storage_configurations`, etc.

### Proposal

`
terraform import databricks_mws_workspaces.this <workspace-id>
`

**Comment by nfx** [comment] 2023-04-06 16:32
they're improtable - `<account_id>/<actual_id>`. but users still make mistakes in importing it. so it'll be fixed by adding the second terraform provider.

all resources in this terraform provider are importable, except one or two.

**Closed by nfx** 2023-04-06 16:32 UTC
Labels: feature

**Comment by frosforever** [comment] 2023-09-08 14:20
`databricks_mws_workspaces` is still labeled as "Importing this resource is not currently supported." I'm guessing this fits into the "except one or two" you refer to. Is this by design and will never be importable or is the plan to be able to import this in the future?

**Comment by gabriellesc** [comment] 2023-11-04 22:45
I was able to successfully import the following resource types using the `<account_id>/<resource_id>` syntax suggested by @nfx:
- `databricks_mws_networks`
- `databricks_mws_credentials`
- `databricks_mws_storage_configurations`
- `databricks_mws_workspaces`
- `databricks_mws_customer_managed_keys`

I was also able to successfully import the `databricks_mws_log_delivery` resource type using `<account_id>|<resource_id>`.
