### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource

### ISSUE THREAD

**Issue by roelofvsr** [databricks/terraform-provider-databricks#1749] opened 2022-11-10 15:44 UTC
### Configuration
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.29"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.6"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.4"
    }
  }

  backend "azurerm" {}
}
```

### Expected Behavior
terraform init and install of provider without any issue

### Actual Behavior
intermittent error:
"failed to install provider: TLS handshake timeout"

![Screenshot 2022-11-10 at 16 37 16](https://user-images.githubusercontent.com/17225298/201138663-ebc960d2-d2a8-489a-b483-158ef11a8e8a.png)

### Steps to Reproduce
- place basic config in azure dev/ops repo
- set up basic pipeline that executes a `tf init` on azure hosted ubuntu agent
- run pipeline couple of times until failure

agent info:
```
Current agent version: '2.213.1'
Operating System
Ubuntu
20.04.5
```

### Terraform and provider versions
tfversion:
`Terraform v1.3.4 on linux_amd64`

databricks:
`registry.terraform.io/databricks/databricks v1.6.4`

### Debug Output
error is intermittent: I have turned on logging, will update once error occurs again

### Important Factoids
using install terraform task from charles zipp:
https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform

possibly related but older:
https://github.com/hashicorp/terraform/issues/31341
https://github.com/databricks/terraform-provider-databricks/pull/966

**Comment by nfx** [comment] 2022-11-15 12:46
@roelofvsr https://github.com/databricks/terraform-provider-databricks/pull/966 is retrying on TLS timeout for requests made by Databricks Provider to Databricks REST APIs.

This is really a duplicate of https://github.com/hashicorp/terraform/issues/31341, where TLS timeout is not retried by Terraform CLI not making retries to GitHub REST APIs to download a release. 

You should retry your AzDo pipelines if this intermittent error happens.

**Closed by nfx** 2022-11-15 12:46 UTC
Labels: invalid
