### ISSUE TITLE
[FEATURE] Support Allowlist libraries and init scripts configuration on metastore level

### ISSUE THREAD

**Issue by VOVELEE** [databricks/terraform-provider-databricks#2782] opened 2023-10-09 11:13 UTC
### Use-cases

Support managing allowlist of libraries and init scripts configuration on metastore level.
The API already support it.

### Attempted Solutions

- Based on my knowledge the provider does not support it at the moment

### Proposal

- Implement `databricks_artifact_allowlist` resource which is able to configure allowed volume locations for "INIT_SCRIPT", "LIBRARY_JAR" and "LIBRARY_MAVEN" 

### References

- Documentation: https://learn.microsoft.com/en-us/azure/databricks/data-governance/unity-catalog/manage-privileges/allowlist
- API reference: https://docs.databricks.com/api/workspace/artifactallowlists

**Comment by alexott** [comment] 2023-10-09 11:21
PR is already opened: #2744. This is a duplicate of #2688

**Closed by alexott** 2023-10-09 11:21 UTC
Labels: feature

**Comment by VOVELEE** [comment] 2023-10-09 11:22
@alexott thanks :)
