### ISSUE TITLE
[ISSUE] Provider issue when destroying databricks cluster

### ISSUE THREAD

**Issue by yavorivanov-cw** [databricks/terraform-provider-databricks#1494] opened 2022-07-22 12:31 UTC
We are successfully creating the following configuration in Azure, but afterwards we can't remove created cluster. 

### Configuration
```hcl
> main.tf

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.9.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "1.0.2"
    }
  }
  required_version = ">= 1.1.0"
}

provider "azurerm" {
  features {}
}

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.this.id
}

resource "azurerm_resource_group" "baserg" {
  name     = format("dlv2-%s-rg", var.environment)
  location = var.location
}

resource "azurerm_databricks_workspace" "this" {
  name                        = format("%s-%s-%s-dbws", var.environment, var.project, var.usage)
  resource_group_name         = azurerm_resource_group.baserg.name
  managed_resource_group_name = format("%s-%s-%s-dbrg", var.environment, var.project, var.usage)
  location                    = var.location
  sku                         = "premium"

  public_network_access_enabled = "true"

  custom_parameters {
    no_public_ip             = false
    storage_account_name     = format("%s%s%sdbsa", var.environment, var.project, var.usage)
    storage_account_sku_name = "Standard_LRS"
  }

  timeouts {
    create = "30m"
    update = "30m"
    read   = "30m"
    delete = "30m"
  }
}

resource "databricks_cluster" "clusters" {
  for_each                = var.clusters
  cluster_name            = each.value.cluster_name
  spark_version           = each.value.spark_version
  node_type_id            = each.value.node_type_id
  autotermination_minutes = each.value.autotermination_minutes
  spark_conf              = each.value.spark_conf

  autoscale {
    min_workers = each.value.min_workers
    max_workers = each.value.max_workers
  }
}

resource "databricks_library" "python_sqlalchemy" {
  for_each   = databricks_cluster.clusters
  cluster_id = each.value.id
  pypi {
    package = "sqlalchemy"
  }
}

resource "databricks_library" "java_stocator" {
  for_each   = databricks_cluster.clusters
  cluster_id = each.value.id
  maven {
    coordinates = "com.ibm.stocator:stocator:1.1.4"
  }
}

> variables.tf

variable "location" {
  type    = string
  default = "West Europe"
}

variable "environment" {
  type = string
  default = "none"
}

variable "project" {
    type = string
    default = "cluster"
}

variable "usage" {
    type = string
    default = "test"
}

variable "clusters" {
  type = map(object({
    cluster_name = string
    spark_version = string
    node_type_id            = string
    autotermination_minutes = number
    min_workers             = number
    max_workers             = number
    spark_conf              = map(any)
  }))

  default = {
    management-cluster = {
      cluster_name            = "default-cluster"
      spark_version           = "10.4.x-scala2.12"
      node_type_id            = "Standard_F4s"
      autotermination_minutes = 20
      min_workers             = 1
      max_workers             = 4
      spark_conf              = {}
    },
    fancy-cluster = {
      cluster_name            = "fancy-cluster"
      spark_version           = "10.4.x-scala2.12"
      node_type_id            = "Standard_F8"
      autotermination_minutes = 15
      min_workers             = 1
      max_workers             = 3
      spark_conf = {
        "spark.sql.files.maxRecordsPerFile" = 12345
      }
    }
  }
}
```

### Expected Behavior
After successful deployment of the above configuration, we want to remove the "fancy-cluster". When we remove it from the variables and apply the new configuration with ```terraform apply``` we expect the cluster to be removed.
We also expect when removing a cluster, the ```databricks_mount``` and ```databricks_library``` for the other clusters to remain.

### Actual Behavior
The cluster is not removed with the following error:

    Error: Cycle: module.sndbx_proj1_test.databricks_library.python_sqlalchemy["fancy-cluster"] (destroy), module.sndbx_proj1_test.databricks_cluster.clusters["fancy-cluster"] (destroy), module.sndbx_proj1_test.azurerm_databricks_workspace.this, module.sndbx_proj1_test.output.databricks_workspace_id (expand), provider["registry.terraform.io/databricks/databricks"].sndbx_proj1_test, module.sndbx_proj1_test.databricks_library.java_stocator["fancy-cluster"] (destroy)

### Steps to Reproduce
1. Create the above deployment
2. `terraform apply`
3. Remove "fancy-cluster" from clusters in variables.tf
4. `terraform apply`

### Workarounds
1. We can destroy the cluster with:

  terraform destroy -target 'module.sndbx_proj1_test.databricks_cluster.clusters["fancy-cluster"]'

but then terraform plans to destroy all ```databricks_mount```. The same is also valid for ```databricks_library```, it plans to destroy for each cluster.

2. Create ```databricks_mount``` without cluster_id. Still ```terraform apply``` is not possible, but now 

  terraform destroy -target 'module.sndbx_proj1_test.databricks_cluster.clusters["fancy-cluster"]'

does not destroy the ```databricks_mount```.

### Terraform and provider versions
Terraform v1.2.5
databricks version = "1.0.2"

### Debug Output
https://gist.github.com/yavorivanov-cw/c1a03db1c3b7f399e436728999741111

**Comment by nfx** [comment] 2022-07-22 14:41
@yavorivanov-cw to massively speed up resolution, Could you make a reproducible configuration for this issue? Please update the one in issue description only with cluster and library resources. Then someone will be able to take entire configuration and reproduce it in their own environment to fix it. Workspace/mount is slow to create…

**Comment by yavorivanov-cw** [comment] 2022-07-25 09:04
> @yavorivanov-cw to massively speed up resolution, Could you make a reproducible configuration for this issue? Please update the one in issue description only with cluster and library resources. Then someone will be able to take entire configuration and reproduce it in their own environment to fix it. Workspace/mount is slow to create…
> 
> it may also look like #1260

Just updated it.

**Comment by nfx** [comment] 2022-08-22 09:08
Duplicate of #1260

**Closed by nfx** 2022-08-22 09:08 UTC
Labels: cannot reproduce
