### ISSUE TITLE
[ISSUE] Issue with aws crossaccount policy: invalid Databricks Workspace configuration

### ISSUE THREAD

**Issue by neox2811** [databricks/terraform-provider-databricks#3446] opened 2024-04-09 15:24 UTC
### Configuration

```hcl
# main.tf

terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.39.0"
    }
  }
}

provider "databricks" {
  profile = "terraform-workspace"
}

provider "databricks" {
  alias   = "accounts"
  profile = "terraform-account"
}

# the following module contains the code of aws-workspace-basic terraform example
module "workspace_production" {
  source = "./modules/db-workspace"

  databricks_account_id = var.databricks_account_id
  prefix                = "production"

  providers = {
    databricks          = databricks.accounts
    databricks.accounts = databricks.accounts
  }
}

# modules/db-workspace/versions.tf
terraform {
  required_providers {
    databricks = {
      source                = "databricks/databricks"
      configuration_aliases = [databricks.accounts]
    }

    aws = {
      source = "hashicorp/aws"
    }
  }
}

```

### Expected Behavior
The workspace should be created.

### Actual Behavior
I get the following error message when running `terraform plan`

```
Plan: 31 to add, 0 to change, 0 to destroy.
╷
│ Error: cannot read aws crossaccount policy: cannot get client aws crossaccount policy: invalid Databricks Workspace configuration
│ 
│   with module.workspace_production.data.databricks_aws_crossaccount_policy.this,
│   on modules/db-workspace/data.tf line 5, in data "databricks_aws_crossaccount_policy" "this":
│    5: data "databricks_aws_crossaccount_policy" "this" {
│ 
```
### Steps to Reproduce
see above. I also tried to paste all ressources of the [aws-workspace-basic](https://github.com/databricks/terraform-databricks-examples/tree/main/modules/aws-workspace-basic) module into one file in the root module - that works for me, so there is no general problem with my providers I guess.

I also added the `databricks.accounts` provider for all `databricks_mws_*` ressources in the module.

### Terraform and provider versions
Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.39.0
+ provider registry.terraform.io/hashicorp/aws v5.44.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.11.1

### Debug Output
I did not find anything relevant in the Debug Output.

**Comment by alexott** [comment] 2024-04-11 06:24
Duplicate of #3421

**Closed by alexott** 2024-04-11 06:24 UTC
