### ISSUE TITLE
[ISSUE] Issue with `databricks_pipeline` resource - Single Node Cluster

### ISSUE THREAD

**Issue by bnugent2** [databricks/terraform-provider-databricks#2870] opened 2023-11-02 04:49 UTC
Hi,

I'm running into an issue when attempting to create a DLT pipeline with a single node cluster. I'm following the example outlined in the cluster resource [documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#fixed-size-or-autoscaling-cluster) to create a single node cluster and have confirmed that works as expected with a standalone cluster resource however with the same configuration within the `databricks_pipeline` cluster block doesn't create a single node cluster.
### Configuration

```hcl
resource "databricks_pipeline" "dlt_pipeline" {
  name     = "dlt-pipeline"
  storage  = "/storage/pipeline"

  cluster {
    label        = "default"
    node_type_id = "c5.2xlarge"
    num_workers  = 0
    spark_conf = {
      # Single-node
      "spark.databricks.cluster.profile" = "singleNode",
      "spark.master"                     = "local[*]"
    }

    custom_tags = {
      "ResourceClass" = "SingleNode"
    }

  }

  library {
    notebook {
      path = "/example_path"
    }
  }
}
```

### Expected Behavior
A single node cluster should be configured for the pipeline ie. number of workers set to zero.  
![image](https://github.com/databricks/terraform-provider-databricks/assets/60399325/411c0951-e8fe-4903-91f6-3668a90ce984)
### Actual Behavior
The cluster configuration for the pipeline are set to autoscaling with 1-5 workers.
![image](https://github.com/databricks/terraform-provider-databricks/assets/60399325/5c7299e0-de45-46f5-8aa9-d5d55673ae3d)

### Steps to Reproduce
1. run `terraform apply` to create the `databricks_pipeline` resource

### Terraform and provider versions
- Terraform version 1.3.3
- Databricks provider version 1.29.0

**Comment by alexott** [comment] 2023-11-02 07:47
Duplicate of #1875, fixed in #2852 (not released yet)

**Closed by alexott** 2023-11-02 07:47 UTC
