### ISSUE TITLE
[FEATURE] workspace files

### ISSUE THREAD

**Issue by taketarouex** [databricks/terraform-provider-databricks#2244] opened 2023-04-26 02:40 UTC
First of all, thank you for maintaining this valuable provider that has helped many developers in their projects. I hope you are doing well.
I wanted to bring your attention to a recent update on Databricks.
On 4/21, a new feature `workspace files` was introduced and became Generally Available.

Considering the potential benefits of this functionality, I kindly request you to consider implementing support for the new feature in the provider.

Here is a brief overview of the new feature:

- Feature name: Workspace Files
- Feature description: A workspace file is any file in the Databricks workspace that is not a Databricks notebook. Workspace files can be any file type.
https://docs.databricks.com/files/workspace.html

### Use-cases

Managing Workspace Files with Terraform through the provider.

### Attempted Solutions

I apologize for not being able to provide any attempted solutions or technical proposals at this moment as I'm currently not familiar enough with the underlying implementation details.
However, I would be more than happy to help with testing or providing feedback once the feature is being worked on.

### Proposal

As I do not have sufficient knowledge about the provider’s internals, I am unable to provide a specific proposal.

**Comment by alexott** [comment] 2023-04-26 07:00
duplicate of #2206

**Closed by alexott** 2023-04-26 07:00 UTC
Labels: feature
