### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_endpoint` resource

### ISSUE THREAD

**Issue by shreyas-goenka** [databricks/terraform-provider-databricks#1522] opened 2022-08-07 11:03 UTC
### Configuration
```hcl
# Copy-paste your Terraform configuration here
```

resource "databricks_sql_endpoint" "this" {
  name             = "Blue"
  cluster_size     = "Small"
  max_num_clusters = 1

  tags {
    custom_tags {
      key   = "City"
      value = "Amsterdam"
    }
  }
}

### Expected Behavior

In the case where the warehouse already exists in a stopped state, `terraform apply` should start this warehouse

### Actual Behavior

`terraform apply` does not start the warehouse

**Comment by alexott** [comment] 2022-08-08 07:13
It's not expected that Terraform is responsible for starting of the SQL Warehouse if it's stopped. Terraform's job is make sure that configuration is correct, not perform actions like start/stop

**Comment by shreyas-goenka** [comment] 2022-08-08 08:06
We have a field called num_clusters in the configuration which is 0 when the cluster is stopped and 1 when it is not. 

Here is the result of terraform plan when the warehouse already exists in a STOPPED state

```

shreyas.goenka@THW32HFW6T terraform-demo % terraform plan
databricks_sql_endpoint.this: Refreshing state... [id=428e1420a5de9fb5]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # databricks_sql_endpoint.this will be updated in-place
  ~ resource "databricks_sql_endpoint" "this" {
        id                        = "428e1420a5de9fb5"
        name                      = "Blue"
      ~ num_clusters              = 0 -> 1
        # (10 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

However terraform apply does not apply to this plan. 

We see different behaviors when a warehouse already exists vs when it does not. If the warehouse does not exist then terraform waits until the warehouse is in a started state before claiming `terraform apply` is complete which that's not the case for a warehouse does not exist.

**Comment by nfx** [comment] 2022-08-08 12:26
Duplicate of #1204

**Closed by nfx** 2022-08-08 12:26 UTC
