### ISSUE TITLE
[ISSUE] Issue with `databricks_permissions` resource: cannot change permissions when I am owner

### ISSUE THREAD

**Issue by MigQ2** [databricks/terraform-provider-databricks#2407] opened 2023-06-15 00:05 UTC
### Configuration
```hcl

resource "databricks_permissions" "this" {
  job_id = databricks_job.this.id
  access_control {
    user_name        = "my_email@mydomain.com"
    permission_level = "IS_OWNER"
  }

}
```

### Expected Behavior
`terraform apply` works fine and the permissions for the job are properly applied

### Actual Behavior
I get the following error: `Error: cannot create permissions: it is not possible to decrease administrative permissions for the current user`

### Steps to Reproduce
1.  Create a job with Terraform with the permissions block I linked above

### Terraform and provider versions
1.19.0

### Additional information

- In the UI I see am the creator and owner of the job for which I am trying to set permissions
- I have other jobs where I am owner (they run as my user) but not creator and those work fine when I apply terraform with the same permissions block for that job
- I am a workspace admin
- Also I found a related broken link in the docs: the `removes` link [here](https://github.com/databricks/terraform-provider-databricks/blob/master/docs/resources/permissions.md?plain=1#L11) gives a 404

**Comment by efranceschi** [comment] 2023-11-12 23:21
It seems to be a duplicate of #2678.

**Comment by MigQ2** [comment] 2023-11-13 01:32
> It seems to be a duplicate of #2678.

Hi @efranceschi , I don't think it is. I have re-run with 1.29.0 and the issue still persists.

However it might be related to some extent

**Closed** 2024-10-01 11:29 UTC
