### ISSUE TITLE
[FEATURE] datasource databricks_metastore

### ISSUE THREAD

**Issue by terrymunro** [databricks/terraform-provider-databricks#2347] opened 2023-05-29 03:04 UTC
### Use-cases

Creating a Unity Catalog metastore in Azure through terraform is challenging because of the requirement that the first user must be a Global Administrator.
(I probably could have given the service-principal account admin after creating the workspace and logging in with global admin, but I didn't in this case)

So after creating it manually, we still need to give its ID to the other resources such as `databricks_catalog`, `databricks_schema`, ...etc.

It would be nice if we could atleast have a:
```hcl
data "databricks_metastore" "this" {
    name = "unity-catalog"
}
```
to allow us to read in the ID for use in subsequent resources.

### Attempted Solutions

I can retrieve the ID through the admin portal and use it as a variable in terraform.

### Proposal

Add a new datasource, that takes the name of the metastore and can export the ID.

But, I assume the reason this doesn't already exist is because there isn't a REST API for this. So maybe an alternative, proposed solution could be:

Add metastore_id as part of the export to the `databricks_catalogs` ([link](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/catalogs#attribute-reference)).
The REST API for that, does include the metastore ID in its result.
It's not ideal because you might not have any catalogs for some reason, but its something.

**Comment by alexott** [comment] 2023-05-30 06:45
duplicate of #1651

**Closed by alexott** 2023-05-30 06:45 UTC
Labels: feature
