### ISSUE TITLE
[FEATURE] Add subscriptions to SQL Alert job tasks

### ISSUE THREAD

**Issue by orolega** [databricks/terraform-provider-databricks#2436] opened 2023-06-28 05:13 UTC
### Use-cases

Currently there is no way of adding subscriptions (destinations and users) to an alert itself. This must be done via the GUI. However API also does not appear to have this functionality for alerts. There are SQL alert tasks in a job where you can also define subscriptions. These jobs also allow you to schedule when to check the alert (feature also missing on just an alert object in the api and thus terraform). However still lacks the ability to define those subscriptions in the terraform resource. It is possible to define them if creating the job via the API.

So ultimately the use case is being able to add subscriptions to alerts beyond just the creator of them.

### Attempted Solutions

No solution possible given existing features. Must use the API directly

### Proposal

Enable the functionality of the [Job API](https://docs.databricks.com/api/workspace/jobs/create) that adds subscriptions to the existing [SQL Alert Task](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#sql_task-configuration-block) resource

**Comment by alexott** [comment] 2023-06-28 06:49
duplicate of #1983

**Comment by orolega** [comment] 2023-06-29 00:34
> duplicate of #1983

Dont think its a duplicate given what I am proposing does have an API endpoint. In the other ticket you claim it does not. 

TBH I think its just adding the subscriptions object [here](https://github.com/databricks/terraform-provider-databricks/blob/37b4320294617554d4d24dd5413d8489bb969442/jobs/resource_job.go#L72)


from the API documentation. Sorry the formatting is off:

`alertobject
 If alert, indicates that this job must refresh a SQL alert.
alert_idrequiredstring
 The canonical identifier of the SQL alert.
subscriptions
Array of objects
 If specified, alert notifications are sent to subscribers.
Array
user_namestring
 The user name to receive the subscription email.
destination_idstring
 The canonical identifier of the destination to receive email notification.`

**Comment by orolega** [comment] 2023-06-29 00:38
definitely not a duplicate. The other ticket is about creating a destination. I am requesting assigning an existing one to the list of subscriptions when creating a SQL alert task. See the below screen cap

![image](https://github.com/databricks/terraform-provider-databricks/assets/52148348/07f4f8bd-00a1-423f-8995-ccef26508347)

**Comment by orolega** [comment] 2023-06-29 00:45
Currently the [terraform resource](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#alert) only has `alert - (Optional) block consisting of single string field: alert_id - identifier of the Databricks SQL Alert.`

subscriptions and pause_subscriptions should be added per the API

**Comment by alexott** [comment] 2023-06-29 06:19
ah, sorry - misread it...

**Comment by orolega** [comment] 2023-06-29 23:41
beat me to a PR. spent some time yesterday figuring this out. Was trying to test the binary locally to be sure... Anyways, thanks for solving this!

**Comment by alexott** [comment] 2023-06-30 06:09
for development you can use this approach: https://developer.hashicorp.com/terraform/cli/config/config-file#development-overrides-for-provider-developers

but frankly speaking, we had some problems with docs, so it would be hard to get it correct using only the api spec.

**Closed** 2023-07-06 09:43 UTC
Labels: feature, needs-api
