### ISSUE TITLE
[ISSUE] Issue with `databricks_grants` resource

### ISSUE THREAD

**Issue by mahmunij** [databricks/terraform-provider-databricks#2705] opened 2023-09-20 14:34 UTC
Greeting 👋,

I am having troubles when managing grants from multiple sources (IaC repos, UI). Suppose we have a schema with a grant that are not managed by terraform. Whenever we want to grant additional permissions, the existing ones are gone.

In the following example our schema is `foo.bar`, and `Alice` has `USE_SCHEMA` permission. Whenever we are adding `Bob` using terraform, only `Bob` has `USE_SCHEMA` permission.  

### Configuration
```hcl
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
      version = "1.26.0"
    }
  }
}

provider "databricks" {}

resource "databricks_grants" "things" {
  schema = "foo.bar"
  grant {
    principal  = "Bob"
    privileges = ["USE_SCHEMA"] 
  }
}
```

### Expected Behavior

Both `Alice` and `Bob` should have `USE_SCHEMA` permission on `foo.bar`

### Actual Behavior

Only `Bob` has `USE_SCHEMA` permission on `foo.bar`

### Steps to Reproduce

1. Create a schema using databricks web-ui/cli/API
1. Create a grant with any principal and permission on that schema
1. Define grant in terraform code on that schema to add additional permissions
1. Apply terraform code

### Terraform and provider versions

```
Terraform v1.5.6
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.26.0
```

<details>
<summary> Debug Output</summary>

```sh
2023-09-20T16:22:01.879+0200 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 args=[.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=772
2023-09-20T16:22:01.879+0200 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0
2023-09-20T16:22:01.887+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Databricks Terraform Provider
2023-09-20T16:22:01.887+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.887+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Version 1.26.0
2023-09-20T16:22:01.887+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.887+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: https://registry.terraform.io/providers/databricks/databricks/latest/docs
2023-09-20T16:22:01.887+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.887+0200 [INFO]  provider.terraform-provider-databricks_v1.26.0: configuring server automatic mTLS: timestamp=2023-09-20T16:22:01.887+0200
network=unix address=/tmp/plugin1588086632 timestamp=2023-09-20T16:22:01.904+0200
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=772
2023-09-20T16:22:01.925+0200 [DEBUG] ProviderTransformer: "databricks_grants.things" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databricks/databricks"]
2023-09-20T16:22:01.925+0200 [DEBUG] ReferenceTransformer: "databricks_grants.things" references: []
2023-09-20T16:22:01.925+0200 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databricks/databricks\"]" references: []
2023-09-20T16:22:01.930+0200 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 args=[.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=790
2023-09-20T16:22:01.930+0200 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0
2023-09-20T16:22:01.938+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Databricks Terraform Provider
2023-09-20T16:22:01.938+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.938+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Version 1.26.0
2023-09-20T16:22:01.938+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.938+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: https://registry.terraform.io/providers/databricks/databricks/latest/docs
2023-09-20T16:22:01.938+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.938+0200 [INFO]  provider.terraform-provider-databricks_v1.26.0: configuring server automatic mTLS: timestamp=2023-09-20T16:22:01.938+0200
address=/tmp/plugin3817984983 network=unix timestamp=2023-09-20T16:22:01.955+0200
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=790
2023-09-20T16:22:01.974+0200 [DEBUG] ProviderTransformer: "databricks_grants.things (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/databricks/databricks"]
2023-09-20T16:22:01.974+0200 [DEBUG] ReferenceTransformer: "databricks_grants.things (expand)" references: []
2023-09-20T16:22:01.974+0200 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databricks/databricks\"]" references: []
2023-09-20T16:22:01.980+0200 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 args=[.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=805
2023-09-20T16:22:01.980+0200 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0
2023-09-20T16:22:01.986+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Databricks Terraform Provider
2023-09-20T16:22:01.986+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.986+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Version 1.26.0
2023-09-20T16:22:01.986+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.986+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: https://registry.terraform.io/providers/databricks/databricks/latest/docs
2023-09-20T16:22:01.986+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:01.986+0200 [INFO]  provider.terraform-provider-databricks_v1.26.0: configuring server automatic mTLS: timestamp=2023-09-20T16:22:01.986+0200
address=/tmp/plugin2323443229 network=unix timestamp=2023-09-20T16:22:02.004+0200
2023-09-20T16:22:02.024+0200 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/databricks/databricks\"]" changed the config value, but that value is unused
2023-09-20T16:22:02.024+0200 [INFO]  provider.terraform-provider-databricks_v1.26.0: Explicit and implicit attributes:: timestamp=2023-09-20T16:22:02.024+0200
2023-09-20T16:22:02.024+0200 [DEBUG] Resource instance state not found for node "databricks_grants.things", instance databricks_grants.things
2023-09-20T16:22:02.024+0200 [DEBUG] ReferenceTransformer: "databricks_grants.things" references: []
2023-09-20T16:22:02.025+0200 [DEBUG] refresh: databricks_grants.things: no state, so not refreshing
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=805
2023-09-20T16:22:02.028+0200 [DEBUG] Resource state not found for node "databricks_grants.things", instance databricks_grants.things
2023-09-20T16:22:02.028+0200 [DEBUG] ProviderTransformer: "databricks_grants.things (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/databricks/databricks"]
2023-09-20T16:22:02.028+0200 [DEBUG] ProviderTransformer: "databricks_grants.things" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/databricks/databricks"]
2023-09-20T16:22:02.028+0200 [DEBUG] ReferenceTransformer: "databricks_grants.things (expand)" references: []
2023-09-20T16:22:02.028+0200 [DEBUG] ReferenceTransformer: "databricks_grants.things" references: []
2023-09-20T16:22:02.028+0200 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databricks/databricks\"]" references: []
  # databricks_grants.things will be created
  + resource "databricks_grants" "things" {
2023-09-20T16:22:36.798+0200 [DEBUG] Resource state not found for node "databricks_grants.things", instance databricks_grants.things
2023-09-20T16:22:36.798+0200 [DEBUG] ProviderTransformer: "databricks_grants.things (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/databricks/databricks"]
2023-09-20T16:22:36.798+0200 [DEBUG] ProviderTransformer: "databricks_grants.things" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/databricks/databricks"]
2023-09-20T16:22:36.798+0200 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databricks/databricks\"]" references: []
2023-09-20T16:22:36.798+0200 [DEBUG] ReferenceTransformer: "databricks_grants.things (expand)" references: []
2023-09-20T16:22:36.798+0200 [DEBUG] ReferenceTransformer: "databricks_grants.things" references: []
2023-09-20T16:22:36.803+0200 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 args=[.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=819
2023-09-20T16:22:36.804+0200 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0
2023-09-20T16:22:36.814+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Databricks Terraform Provider
2023-09-20T16:22:36.814+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:36.814+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: Version 1.26.0
2023-09-20T16:22:36.814+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:36.814+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: https://registry.terraform.io/providers/databricks/databricks/latest/docs
2023-09-20T16:22:36.814+0200 [DEBUG] provider.terraform-provider-databricks_v1.26.0: 
2023-09-20T16:22:36.814+0200 [INFO]  provider.terraform-provider-databricks_v1.26.0: configuring server automatic mTLS: timestamp=2023-09-20T16:22:36.814+0200
address=/tmp/plugin1429343795 network=unix timestamp=2023-09-20T16:22:36.832+0200
2023-09-20T16:22:36.852+0200 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/databricks/databricks\"]" changed the config value, but that value is unused
2023-09-20T16:22:36.853+0200 [INFO]  provider.terraform-provider-databricks_v1.26.0: Explicit and implicit attributes:: timestamp=2023-09-20T16:22:36.853+0200
databricks_grants.things: Creating...
2023-09-20T16:22:36.857+0200 [INFO]  Starting apply for databricks_grants.things
2023-09-20T16:22:36.857+0200 [DEBUG] databricks_grants.things: applying the planned Create change
databricks_grants.things: Creation complete after 1s [id=schema/foo.bar]
path=.terraform/providers/registry.terraform.io/databricks/databricks/1.26.0/linux_amd64/terraform-provider-databricks_v1.26.0 pid=819
```
</details>

**Comment by alexott** [comment] 2023-09-20 15:08
Duplicate of #2704, see discussion there

**Closed by alexott** 2023-09-20 15:08 UTC
