### ISSUE TITLE
[ISSUE] Provider issue

### ISSUE THREAD

**Issue by barywhyte** [databricks/terraform-provider-databricks#1451] opened 2022-07-12 19:07 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
```
terraform {
  required_version = "0.13.7"
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.4.6"
    }
  }
}

provider "databricks" {
  alias      = "mws"
  host = "https://dbc-xxxxxxxxxx.cloud.databricks.com/"
  account_id = "xxxxxxxx"
}

# Databricks Users and Groups Access Policy
resource "databricks_group" "eng" {
  display_name               = "eng"
  allow_cluster_create       = false
  allow_instance_pool_create = false
  workspace_access           = true
  databricks_sql_access      = true
}

resource "databricks_user" "bot_user" {
  provider     = databricks.mws
  user_name    = "bot-user@mydomain.io"
  display_name = "BOT USER"
}

resource "databricks_group_member" "eng_member" {
  group_id  = databricks_group.eng.id
  member_id = databricks_user.bot_user.id
}
```

### Expected Behavior
Everything looked fine after `terraform apply` in my feature git branch

### Actual Behavior
In the master branch, however, `terraform plan` got broken

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

### Terraform and provider versions
terraform version
```
Terraform v0.13.7
```
### Debug Output
https://gist.github.com/barywhyte/0799108e9791ad20bc2a98df73223d5a

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
The real problem is that, after successful `terraform apply` as described above, subsequent `terraform plan` results in broken state with the below error:
```
Error: Provider configuration not present

To work with
module.databricks_workspace.module.databricks_user_permissions.databricks_user.bot_user
its original provider configuration at
module.databricks_workspace.module.databricks_user_permissions.provider["registry.terraform.io/databrickslabs/databricks"].mws
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.databricks_workspace.module.databricks_user_permissions.databricks_user.bot_user,
after which you can remove the provider configuration again.
```

**Comment by nfx** [comment] 2022-07-12 19:12
Duplicate of #1389 

Please follow https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting#error-failed-to-install-provider

**Closed by nfx** 2022-07-12 19:12 UTC
