### ISSUE TITLE
cannot read aws crossaccount policy: cannot get client aws crossaccount policy: invalid Databricks Workspace configuration

### ISSUE THREAD

**Issue by JanuaryThomas** [databricks/terraform-provider-databricks#3451] opened 2024-04-10 17:09 UTC
Hi I can not create databricks resources due to databricks cross account policy in terraform provider 1.39.0

I'm having this error
"cannot read aws crossaccount policy: cannot get client aws crossaccount policy: invalid Databricks Workspace configuration"

I've reverted back to version 1.37.0 and everthing works fine

### Affected Resource(s)
data "databricks_aws_crossaccount_policy" "cross_account_policy" {}  in databricks provider version 1.39.0

**Comment by alexott** [comment] 2024-04-11 06:25
Duplicate of #3421

**Closed by alexott** 2024-04-11 06:25 UTC
Labels: docs
