### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource

### ISSUE THREAD

**Issue by michaelvonderbecke** [databricks/terraform-provider-databricks#2593] opened 2023-08-17 21:00 UTC
### Configuration
My hcl is dozens of pages long and not feasible to paste here.  Suffice to say if I try to specify a run_job_task like so:

```
run_job_task {
  job_id = somejobid
}
```
Everything breaks

### Expected Behavior
Job task should be linked to the specified job id and everything should exit successfully

### Actual Behavior
Job task is correctly linked to target job, but terraform aborts with the following error:
Error: cannot read job: json: cannot unmarshal number into Go struct field RunJobTask.settings.tasks.run_job_task.job_id of type string

It's no longer possible to execute a terraform plan against the terraform at all without it aborting with the above error - the only resolution is to manually delete the job and remove it from the terraform state

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
TF: 1.5.3
databricks provider: 1.23.0

### Debug Output
```
2023-08-17T16:58:17.142-0400 [DEBUG] ReferenceTransformer: "module.databricks_job[\"second-job\"].databricks_job.this[0]" references: []
module.databricks_job["example-job"].databricks_job.this[0]: Refreshing state... [id=132914375191887]
module.databricks_job["second-job"].databricks_job.this[0]: Refreshing state... [id=482841085361114]
2023-08-17T16:58:17.250-0400 [DEBUG] provider.terraform-provider-databricks_v1.23.0: Suppressing diff for name=webhook_notifications.# k="webhook_notifications.#" platform="1" config="0": timestamp=2023-08-17T16:58:17.249-0400
2023-08-17T16:58:17.250-0400 [DEBUG] provider.terraform-provider-databricks_v1.23.0: Suppressing diff for task.0.run_if: platform="ALL_SUCCESS" config="": timestamp=2023-08-17T16:58:17.250-0400
2023-08-17T16:58:17.251-0400 [DEBUG] provider.terraform-provider-databricks_v1.23.0: Suppressing diff for task.0.new_cluster.0.data_security_mode: platform="SINGLE_USER" config="": timestamp=2023-08-17T16:58:17.251-0400
2023-08-17T16:58:17.251-0400 [DEBUG] provider.terraform-provider-databricks_v1.23.0: Suppressing diff for name=task.0.email_notifications.# k="task.0.email_notifications.#" platform="1" config="0": timestamp=2023-08-17T16:58:17.251-0400
2023-08-17T16:58:17.267-0400 [WARN]  Provider "registry.terraform.io/databricks/databricks" produced an invalid plan for module.databricks_job["example-job"].databricks_job.this[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .timeout_seconds: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .always_running: planned value cty.False for a non-computed attribute
      - .control_run_state: planned value cty.False for a non-computed attribute
      - .min_retry_interval_millis: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .task[0].compute_key: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].min_retry_interval_millis: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .task[0].description: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].existing_cluster_id: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].job_cluster_key: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].run_if: planned value cty.StringVal("ALL_SUCCESS") for a non-computed attribute
      - .task[0].email_notifications: block count in plan (1) disagrees with count in config (0)
      - .task[0].new_cluster[0].apply_policy_default_values: planned value cty.False for a non-computed attribute
      - .task[0].new_cluster[0].cluster_id: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].data_security_mode: planned value cty.StringVal("SINGLE_USER") for a non-computed attribute
      - .task[0].new_cluster[0].autotermination_minutes: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .task[0].new_cluster[0].instance_pool_id: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].single_user_name: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].ssh_public_keys: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .task[0].new_cluster[0].cluster_name: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].runtime_engine: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].idempotency_token: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].aws_attributes[0].ebs_volume_count: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .task[0].new_cluster[0].aws_attributes[0].ebs_volume_size: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .task[0].new_cluster[0].aws_attributes[0].ebs_volume_type: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].cluster_log_conf[0].s3[0].canned_acl: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].cluster_log_conf[0].s3[0].enable_encryption: planned value cty.False for a non-computed attribute
      - .task[0].new_cluster[0].cluster_log_conf[0].s3[0].encryption_type: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].cluster_log_conf[0].s3[0].endpoint: planned value cty.StringVal("") for a non-computed attribute
      - .task[0].new_cluster[0].cluster_log_conf[0].s3[0].kms_key: planned value cty.StringVal("") for a non-computed attribute
      - .email_notifications[0].alert_on_last_attempt: planned value cty.False for a non-computed attribute
      - .email_notifications[0].no_alert_for_skipped_runs: planned value cty.False for a non-computed attribute
      - .email_notifications[0].on_duration_warning_threshold_exceeded: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .webhook_notifications: block count in plan (1) disagrees with count in config (0)
2023-08-17T16:58:17.305-0400 [ERROR] provider.terraform-provider-databricks_v1.23.0: Response contains error diagnostic: diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="cannot read job: json: cannot unmarshal number into Go struct field RunJobTask.settings.tasks.run_job_task.job_id of type string" tf_proto_version=5.3 tf_req_id=19d03380-44ed-631f-c5ec-86c7febfa147 @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/diag/diagnostics.go:58 tf_resource_type=databricks_job tf_rpc=ReadResource @module=sdk.proto tf_provider_addr=registry.terraform.io/databricks/databricks timestamp=2023-08-17T16:58:17.304-0400
2023-08-17T16:58:17.305-0400 [ERROR] vertex "module.databricks_job[\"second-job\"].databricks_job.this[0]" error: cannot read job: json: cannot unmarshal number into Go struct field RunJobTask.settings.tasks.run_job_task.job_id of type string
2023-08-17T16:58:17.305-0400 [ERROR] vertex "module.databricks_job.databricks_job.this (expand)" error: cannot read job: json: cannot unmarshal number into Go struct field RunJobTask.settings.tasks.run_job_task.job_id of type string

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: cannot read job: json: cannot unmarshal number into Go struct field RunJobTask.settings.tasks.run_job_task.job_id of type string
│ 
│   with module.databricks_job["second-job"].databricks_job.this[0],
│   on .terraform/modules/databricks_job/main.tf line 283, in resource "databricks_job" "this":
│  283: resource "databricks_job" "this" {
```

### Important Factoids
N/A

**Comment by majidfn** [comment] 2023-08-17 21:26
duplicate of: https://github.com/databricks/terraform-provider-databricks/issues/2582

**Comment by nkvuong** [comment] 2023-08-17 22:06
Duplicate of #2582

**Closed by nkvuong** 2023-08-17 22:06 UTC
