### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster` resource

### ISSUE THREAD

**Issue by thaiphv** [databricks/terraform-provider-databricks#3553] opened 2024-05-08 00:33 UTC
### Configuration
```hcl
data "databricks_node_type" "smallest" {
  local_disk = true
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Shared Autoscaling"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 50
  }
}
```

### Expected Behavior
The cluster should have been created.

### Actual Behavior
The provider failed to create the cluster with the error:
```
Error: cannot update cluster: The specified IOPS, 0, is not in the range 3,000 - 16,000
```

This works fine with `1.41.0`

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
TF version: 1.6.5
Databricks provider version: 1.42.0

**Comment by andrewnester** [comment] 2024-05-14 12:04
Fixed in 1.43.0 version

**Closed by andrewnester** 2024-05-14 12:04 UTC

**Comment by lcysimon** [comment] 2024-05-15 08:23
I am not sure it is properly fixed @andrewnester 
. While the initial apply / upgrade works, further modification will fail:

I cannot update any `aws_attributes` of our clusters when already in version `1.43.0`. Just changing the availability from `SPOT` to `SPOT_WITH_FALLBACK` will cause the same issue.

To reproduce:
```
data "databricks_node_type" "smallest" {
  local_disk = true
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Shared Autoscaling"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20

  aws_attributes {
    availability     = "SPOT" # Change to SPOT_WITH_FALLBACK
    ebs_volume_count = null
    ebs_volume_size  = null
    ebs_volume_type  = null
  }

  autoscale {
    min_workers = 1
    max_workers = 3
  }
}
```

After initial apply, change `SPOT` to `SPOT_WITH_FALLBACK`, you will have the same error message:

<img width="661" alt="Screenshot 2024-05-15 at 10 22 26" src="https://github.com/databricks/terraform-provider-databricks/assets/681402/dbb16d02-e912-401c-b9e0-9e8b0db3a4f7">

**Comment by npfroiland** [comment] 2024-05-16 17:41
I'm seeing the same behavior as described above too for both versions `1.43.0` and `1.44.0`. I also tested changing an attribute outside of the `aws_attributes` and that produced the same error. It looks like any attempted updates to a `databricks_cluster` resource are currently failing to apply.
